#!/bin/bash
#ask the user if he/she wants to see a few random numbers?(Y for yes, N or no)
#demonstrate how to generate random numbers in the specified range [min, max]
min=1
max=50
echo "Do you want me to show you how to generate a few random numbers in the range of [$min, $max] (type Y for Yes or N for No)?"
read usr_option
    
case $usr_option in
    [Yy])howmany=$(((RANDOM % 10) +1))
         echo "I will generate $howmany random numbers in the range of [1, 50]:"
         for ((i=0; i < $howmany; i++))
         do
             rnum=$(((RANDOM % (max - min + 1)) + min))
             echo "No. $((i+1)): $rnum"
         done;;
    [Nn]);;
    *)echo "Your choice is not valid";;
esac
echo "Have a great day!"

