#!/bin/bash
# generate number sequence 
# using command line arguments to set up the range [min, max]
echo "There are $# parameters."
echo "The parameters are $*"
start=$1
end=$2
if [ $1 -gt $2 ]
then 
     start=$2
     end=$1
fi
echo "The starting integer is $start"
echo "The ending integer is $end"
num=$start
n1=1
n2=2
n=$((n1+n2))
if [ $start -le $n1 ]
then 
    echo "$n1"
    echo "$n2"
fi
while [ $n -le $end ]
do
    echo "$n"
    n1=$n2
    n2=$n
    n=$((n1+n2))
done

